In [80]:
import numpy as np
def arrDetail(arr):
    dimention = arr.ndim
    shape = arr.shape
    return f"Dimention : {dimention}, Shape : {shape}"

one_d_arr = np.array([1,2,3,4,5,6,7,8,9])
print(arrDetail(one_d_arr))

two_d_arr = np.array([[1,2],
                      [3,4]])
print(arrDetail(two_d_arr))

three_d_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                        [[1,2,3],[4,5,6],[7,8,9]],
                        [[1,2,3],[4,5,6],[7,8,9]]])
print(arrDetail(three_d_arr))


Dimention : 1, Shape : (9,)
Dimention : 2, Shape : (2, 2)
Dimention : 3, Shape : (3, 3, 3)


In [89]:
import numpy as np
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20]])
print(arr[1:4]) #accessing only row dimension
print()
print(arr[1:4:2]) #accessing only row dimension
print()
print(arr[:,1:4]) #accessing only column dimension
print()
print(arr[:,1:4:2]) #accessing only column dimension
print()
print(arr[1:4,1:4])

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 6  7  8  9 10]
 [16 17 18 19 20]]

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [65]:
import numpy as np
x = np.zeros((2,3))
x = np.identity(3)
x = np.eye(3,4,dtype=int)
x = np.random.randint(5,9,size=(2,3))
x = 2+3*np.random.random((3,4))
x = np.full((8,4),2)
print(x)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
